#!/bin/sh
# ============================================================================
# gen-tc-json-inc.sh — regenerate tc_json_schema.inc from twitch-counts.py
# (Wave E, tc_main.S integration).
#
#   tc_json_schema.inc: the embedded JSON Schema for the report document —
#   json.dumps(report_schema(), indent=2) re-indented +2 under the report's
#   "schema" key, outer braces absorbed into the framing  "schema": {  and
#   },  lines, exactly as json.dump(build_report(report), indent=2) would
#   emit it.  tc_json.S emits the blob verbatim as the document's first key.
#
# Byte-exact snapshot of the Python module's own schema, embedded as .rodata
# so the assembly never has to re-derive JSON text.  The Makefile wires a
# regeneration rule (tc_json.o depends on this .inc; this script is the
# recipe) so the embedded text cannot drift from the Python module.
#
# Usage:  ./gen-tc-json-inc.sh
# ============================================================================
set -eu
cd "$(dirname "$0")"

python3 - <<'PY'
import importlib.util
import json

spec = importlib.util.spec_from_file_location("tw", "twitch-counts.py")
tw = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tw)

txt = json.dumps(tw.report_schema(), indent=2)
lines = txt.split("\n")
# Absorb the outer braces, re-indent the body +2 under the "schema" key.
inner = [("  " + ln if ln else ln) for ln in lines[1:-1]]
blob = '  "schema": {\n' + "\n".join(inner) + "\n  },\n"
data = blob.encode("utf-8")

path = "tc_json_schema.inc"
with open(path, "w", encoding="ascii") as f:
    f.write("// tc_json_schema.inc - the embedded JSON Schema for the report document.\n")
    f.write("// Generated from twitch-counts.py report_schema() with json.dumps(indent=2),\n")
    f.write("// indented +2 to sit under the report's \"schema\" key, exactly as\n")
    f.write("// json.dump(build_report(report), indent=2) would emit it. The schema's\n")
    f.write("// outer braces are absorbed into the framing \"schema\": { and }, lines.\n")
    f.write("// Regenerated by ./gen-tc-json-inc.sh (Makefile: gen-json-inc), do not edit.\n")
    f.write(f"// Blob byte count: {len(data)} (frame lines included)\n")
    f.write("    RODATA\n")
    f.write("    .p2align 2\n")
    f.write("tc_json_schema_blob:\n")
    for line in blob.split("\n"):
        if line == "":
            continue        # blob already ends with a newline
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        f.write(f'    .ascii "{escaped}\\n"\n')
    f.write("tc_json_schema_blob_end:\n")
    f.write("    .equ tc_json_schema_blob_len, tc_json_schema_blob_end - tc_json_schema_blob\n")
print(f"{path}: {len(data)} bytes")
PY