#!/bin/sh
# ============================================================================
# gen-tc-misc-inc.sh — regenerate tc_manual.inc and tc_fish.inc from
# twitch-counts.py (Phase 8, tc_misc.S).
#
#   tc_manual.inc: the --manual body — the module docstring with the
#       {{ENVIRONMENT}} placeholder replaced by environment_manual(), plus
#       the trailing newline print() emits (Python main():  print(
#       __doc__.strip().replace(ENVIRONMENT_PLACEHOLDER, environment_manual())))
#   tc_fish.inc:   the --emit-fish-completions body — fish_completions(
#       command="twitch-counts") plus print()'s trailing newline.
#
# Both are byte-exact snapshots of the Python module's own output, embedded
# as .rodata so the assembly never has to re-derive argparse text.  Wave E
# should wire a regeneration rule into the Makefile (tc_misc.o depends on
# these two .inc files; this script is the recipe) so the embedded text can
# never drift from the Python module.
#
# Usage:  ./gen-tc-misc-inc.sh
# ============================================================================
set -eu
cd "$(dirname "$0")"

python3 - <<'PY'
import importlib.util

spec = importlib.util.spec_from_file_location("tw", "twitch-counts.py")
tw = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tw)

manual = tw.__doc__.strip().replace(tw.ENVIRONMENT_PLACEHOLDER,
                                    tw.environment_manual()) + "\n"
fish = tw.fish_completions("twitch-counts") + "\n"


def emit(path, symbol, text):
    data = text.encode("utf-8") + b"\x00"
    with open(path, "w", encoding="ascii") as f:
        f.write(f"// {path} -- GENERATED by gen-tc-misc-inc.sh, do not edit.\n")
        f.write(f"// Regenerate with: ./gen-tc-misc-inc.sh\n")
        f.write("    RODATA\n")
        f.write("    .p2align 4\n")
        f.write(f"    .global {symbol}\n")
        f.write(f"{symbol}:\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            f.write("    .byte " + ",".join(f"0x{b:02x}" for b in chunk) + "\n")
        f.write(f"{symbol}_end:\n")
        f.write(f"    .global {symbol}_len\n")
        f.write(f"    .equ {symbol}_len, {symbol}_end - {symbol}\n")
    print(f"{path}: {len(data)} bytes")


emit("tc_manual.inc", "tc_manual_text", manual)
emit("tc_fish.inc", "tc_fish_text", fish)
PY