#!/bin/sh
# ============================================================================
# gen-tc-c-inc.sh — regenerate the C string constants c/tc_manual.inc,
# c/tc_fish.inc and c/tc_json_schema.inc from twitch-counts.py.
#
# The C port embeds the same byte-exact text the Python renders for
# --manual, --emit-fish-completions and the JSON Schema.  These headers are
# the C counterparts of the asm/ .inc blobs:
#
#   c/tc_manual.inc      static const char tc_manual_text[]     --manual body
#   c/tc_fish.inc        static const char tc_fish_text_a/b[]   fish completions,
#                        split in two where fish_completions() embeds
#                        shorten_path(DEFAULT_CONFIG_PATH)
#   c/tc_json_schema.inc static const char tc_json_schema_blob[] JSON Schema body
#
# Every array is NUL-terminated; the bytes before the NUL are byte-identical
# to what twitch-counts.py prints (including the trailing newline), so the
# C code can write the constant with fwrite(text, 1, sizeof(text)-1, out).
#
# The constants are COMMITTED sources: the Makefile's `gen-inc` target runs
# this script on request only, never as a build step, because the text
# depends on the machine the Python runs on (default paths).
#
# Usage:  ./gen-tc-c-inc.sh   (or: make gen-inc)
# ============================================================================
set -eu
cd "$(dirname "$0")"

# Output dir for the generated headers; open(path, "w") below never creates
# intermediate directories, so guarantee it exists before the Python runs.
mkdir -p c

python3 - <<'PY'
import importlib.util
import json

spec = importlib.util.spec_from_file_location("tw", "twitch-counts.py")
tw = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tw)

manual = tw.__doc__.strip().replace(tw.ENVIRONMENT_PLACEHOLDER,
                                    tw.environment_manual()) + "\n"
fish = tw.fish_completions("twitch-counts") + "\n"

schema = json.dumps(tw.report_schema(), indent=2)
schema_lines = schema.split("\n")
schema_inner = [("  " + ln if ln else ln) for ln in schema_lines[1:-1]]
schema_blob = '  "schema": {\n' + "\n".join(schema_inner) + "\n  },\n"


def c_escape(text):
    """Escape text for the body of a C string literal, byte-for-byte.

    Printable ASCII stays literal; everything else becomes an escape.
    Non-ASCII bytes use 3-digit octal escapes (never \\x, whose hex runs are
    unbounded), so the source is pure ASCII and the decoded bytes always
    equal the input bytes.
    """
    out = []
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20 or ord(ch) >= 0x7F:
            out.append("\\%03o" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


def emit_array(f, symbol, text):
    """Write one `static const char symbol[]` initializer whose bytes (minus
    the terminating NUL) are exactly `text`.  Each source line becomes an
    adjacent string literal.  A blank line inside the text carries its own
    newline; only the trailing element left by a final newline is empty."""
    lines = text.split("\n")
    f.write(f"/* Byte-identical to what twitch-counts.py renders (including the\n")
    f.write(f" * trailing newline).  NUL-terminated: the byte length is\n")
    f.write(f" * sizeof({symbol}) - 1. */\n")
    f.write(f"static const char {symbol}[] =\n")
    for i, line in enumerate(lines):
        escaped = c_escape(line)
        if i == len(lines) - 1 and text.endswith("\n"):
            f.write('    ""\n')                          # trailing element: no bytes
        elif i == len(lines) - 1:
            f.write('    "' + escaped + '"\n')           # final line, no trailing newline
        else:
            f.write('    "' + escaped + '\\n"\n')        # every other line carries its newline
    f.write("    ;\n\n")


def write_header(f, path, guard, note):
    f.write(f"// {path} -- GENERATED by gen-tc-c-inc.sh, do not edit.\n")
    f.write("// Regenerate with: make gen-inc (./gen-tc-c-inc.sh)\n")
    f.write("// " + note.replace("\n", "\n// ") + "\n")
    f.write("#ifndef " + guard + "\n")
    f.write("#define " + guard + "\n\n")


def write_footer(f, guard):
    f.write("#endif /* " + guard + " */\n")


# -- c/tc_manual.inc ---------------------------------------------------------
path = "c/tc_manual.inc"
with open(path, "w", encoding="ascii") as f:
    write_header(f, path, "TC_MANUAL_INC",
                 "The --manual body: the module docstring with {{ENVIRONMENT}}\n"
                 "replaced by environment_manual(), plus print()'s trailing newline.\n"
                 "Consumed by the C port's --manual handler.")
    emit_array(f, "tc_manual_text", manual)
    write_footer(f, "TC_MANUAL_INC")
print(f"{path}: {len(manual.encode('utf-8'))} bytes")

# -- c/tc_fish.inc -----------------------------------------------------------
# fish_completions() embeds shorten_path(DEFAULT_CONFIG_PATH) (twitch-counts.py
# line 3954), a value the Python computes at runtime for the machine it runs
# on.  The constant is emitted in two parts around that value; the C code
# writes part A, the path it computes the same way, then part B (mirrors
# tc_misc_fish in the assembly port).
marker = "(default: " + tw.shorten_path(tw.DEFAULT_CONFIG_PATH) + ")"
assert fish.count(marker) == 1, marker
cut = fish.index(marker) + len("(default: ")
fish_a = fish[:cut]
fish_b = fish[cut + len(tw.shorten_path(tw.DEFAULT_CONFIG_PATH)):]

path = "c/tc_fish.inc"
with open(path, "w", encoding="ascii") as f:
    write_header(f, path, "TC_FISH_INC",
                 "Fish completions, split in two parts where fish_completions()\n"
                 "embeds shorten_path(DEFAULT_CONFIG_PATH) (twitch-counts.py:3954):\n"
                 "part A ends with '(default: '; the C code writes part A, the\n"
                 "runtime path it computes the same way the Python does, then\n"
                 "part B (mirrors tc_misc_fish in the assembly port).")
    emit_array(f, "tc_fish_text_a", fish_a)
    emit_array(f, "tc_fish_text_b", fish_b)
    write_footer(f, "TC_FISH_INC")
print(f"{path}: {len(fish_a.encode('utf-8')) + len(fish_b.encode('utf-8'))} bytes")

# -- c/tc_json_schema.inc ----------------------------------------------------
path = "c/tc_json_schema.inc"
with open(path, "w", encoding="ascii") as f:
    write_header(f, path, "TC_JSON_SCHEMA_INC",
                 "The embedded JSON Schema for the report document: the same\n"
                 "blob as asm/tc_json_schema.inc (report_schema() with\n"
                 "json.dumps(indent=2), re-indented +2 under the report's\n"
                 "\"schema\" key).  Consumed by the C port's JSON emitter.")
    emit_array(f, "tc_json_schema_blob", schema_blob)
    write_footer(f, "TC_JSON_SCHEMA_INC")
print(f"{path}: {len(schema_blob.encode('utf-8'))} bytes")
PY