#!/bin/sh
# ============================================================================
# gen-tc-misc-inc.sh — regenerate tc_manual.inc and tc_fish.inc from
# twitch-counts.py (tc_misc.S).
#
#   tc_manual.inc: the --manual body — the module docstring with the
#       {{ENVIRONMENT}} placeholder replaced by environment_manual(), plus
#       the trailing newline print() emits (Python main():  print(
#       __doc__.strip().replace(ENVIRONMENT_PLACEHOLDER, environment_manual())))
#   tc_fish.inc:   the --emit-fish-completions body — fish_completions(
#       command="twitch-counts") plus print()'s trailing newline.
#
# Both are byte-exact snapshots of the Python module's own output, embedded
# as .rodata so the assembly never has to re-derive argparse text.  The
# blobs are COMMITTED sources: the Makefile's `gen-inc` target runs this
# script on request only, never as a build step, because the text depends
# on the machine the Python runs on (default paths).
#
# Usage:  ./gen-tc-misc-inc.sh   (or: make gen-inc)
# ============================================================================
set -eu
cd "$(dirname "$0")"

python3 - <<'PY'
import importlib.util

spec = importlib.util.spec_from_file_location("tw", "twitch-counts.py")
tw = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tw)

manual = tw.__doc__.strip().replace(tw.ENVIRONMENT_PLACEHOLDER,
                                    tw.environment_manual()) + "\n"
fish = tw.fish_completions("twitch-counts") + "\n"


def emit(path, symbol, text):
    data = text.encode("utf-8") + b"\x00"
    with open(path, "w", encoding="ascii") as f:
        f.write(f"// {path} -- GENERATED by gen-tc-misc-inc.sh, do not edit.\n")
        f.write(f"// Regenerate with: ./gen-tc-misc-inc.sh\n")
        f.write("    RODATA\n")
        f.write("    .p2align 4\n")
        f.write(f"    .global {symbol}\n")
        f.write(f"{symbol}:\n")
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            f.write("    .byte " + ",".join(f"0x{b:02x}" for b in chunk) + "\n")
        f.write(f"{symbol}_end:\n")
        f.write(f"    .global {symbol}_len\n")
        f.write(f"    .equ {symbol}_len, {symbol}_end - {symbol}\n")
    print(f"{path}: {len(data)} bytes")


emit("tc_manual.inc", "tc_manual_text", manual)

# fish_completions() embeds shorten_path(DEFAULT_CONFIG_PATH) (line 3954),
# a value the Python computes at runtime for the machine it runs on.  The
# blob is emitted in two parts around that value; tc_misc_fish writes part
# A, the path it computes the same way, then part B.
marker = "(default: " + tw.shorten_path(tw.DEFAULT_CONFIG_PATH) + ")"
assert fish.count(marker) == 1, marker
cut = fish.index(marker) + len("(default: ")
fish_a = fish[:cut]
fish_b = fish[cut + len(tw.shorten_path(tw.DEFAULT_CONFIG_PATH)):]


def emit2(path, parts):
    with open(path, "w", encoding="ascii") as f:
        f.write(f"// {path} -- GENERATED by gen-tc-misc-inc.sh, do not edit.\n")
        f.write(f"// Regenerate with: ./gen-tc-misc-inc.sh\n")
        f.write("// Two parts: the runtime default config path goes between them.\n")
        for symbol, text in parts:
            data = text.encode("utf-8") + b"\x00"
            f.write("    RODATA\n")
            f.write("    .p2align 4\n")
            f.write(f"    .global {symbol}\n")
            f.write(f"{symbol}:\n")
            for i in range(0, len(data), 16):
                chunk = data[i:i + 16]
                f.write("    .byte " + ",".join(f"0x{b:02x}" for b in chunk) + "\n")
            f.write(f"{symbol}_end:\n")
            f.write(f"    .global {symbol}_len\n")
            f.write(f"    .equ {symbol}_len, {symbol}_end - {symbol}\n")
            print(f"{path}: {symbol} {len(data)} bytes")


emit2("tc_fish.inc", [("tc_fish_text_a", fish_a), ("tc_fish_text_b", fish_b)])
PY