// ============================================================================
// misc.c — --manual / --emit-fish-completions / --complete.
//
//  The C sibling of asm/tc_misc.S: the --manual body, the fish completions
//  and the --complete candidate helper.  Behavioural oracle: twitch-counts.py
//  main() (manual/fish short-circuit) and completion_candidates +
//  run_completion, byte-for-byte wherever the Python's output is observable.
//
//  What this module owns
//  ---------------------
//    * --manual: print the module docstring with the {{ENVIRONMENT}} marker
//      replaced by environment_manual() plus print()'s newline.  The exact
//      bytes live in c/tc_manual.inc (generated by gen-tc-c-inc.sh).
//    * --emit-fish-completions: fish_completions(command="twitch-counts") plus
//      print()'s newline; exact bytes in c/tc_fish.inc, split in two where
//      fish_completions() embeds shorten_path(DEFAULT_CONFIG_PATH)
//      (twitch-counts.py:3954).  This module writes part A, the default
//      config path it computes the same way the Python does, then part B
//      (mirrors tc_misc_fish in the assembly port).
//    * --complete KIND: run_completion() — candidates for channels, groups,
//      dates, weeks, periods, users, includes, one per line.  A failure
//      prints  completion failed: ConfigError('...')  to stderr and returns
//      0, never a loud exit, exactly like the Python.
//
//  Completion pipeline (mirrors Python completion_candidates + run_completion)
//  ---------------------------------------------------------------------------
//    tc_misc_complete(opts):
//      1. config layer  (load_config_layer)  — a config that fails to LOAD
//         exits 1 loudly (the documented divergence); a missing default path
//         is an empty config.
//      2. channels/groups need no channel; the rest resolve the channel:
//         empty channel -> no output; missing logs root / channel dir ->
//         ConfigError report; the resolved dir drives the remaining kinds.
//      3. dates/weeks/periods: a dated-log listing built here with core.c's
//         tc_parse_log_filename_n (the shared FILENAME_RE filter, date
//         validation and sort), so the parse is the already-tested one.
//      4. users: tc_count_run with a synthetic window (end = now UTC, begin =
//         end - 7d), then most_common() order, then sorted(known - counts).
//      5. includes: the merged exclusion layers (Python build_exclusions)
//         computed here, so its errors stay quiet like run_completion.
//
//  Why the config/channel/exclusions are handled here rather than through
//  config.c/core.c: the config.c hooks only see a --config path once
//  s_opts is registered (after tc_cli_parse's settings resolution), and the
//  core/channel/exclusion paths fail loudly (exit 1) on a bad config or a
//  missing channel — but completion must never fail loudly at a prompt, so
//  the Python catches ConfigError/OSError in run_completion and reports it
//  on stderr with exit 0.  The shared parse helpers (tc_parse_log_filename_n,
//  tc_ascii_casecmp, the calendar arithmetic, tc_count_run) stay reused.
//
//  Deviation notes (shared with the asm port)
//  ------------------------------------------
//    * complete_users uses UTC "now" (the Python uses local time); the
//      differential generates logs that cover any 7-day window.
//    * A config that fails to LOAD (missing explicit path, TOML or I/O error)
//      exits 1 loudly — the documented divergence, shared with the asm port's
//      eager load (the Python reports quietly and exits 0).  Errors AFTER a
//      successful load ([exclude] shape, channel resolution) stay quiet.
//    * Config TOML errors use tomlc99's message ("line N: ...") instead of
//      tomllib's; the "could not read config <path>: " prefix is identical.
//    * The completion module parses the config itself with tomlc99 (it is
//      the first module to see a --config path), so a config that LOADS but
//      fails its [exclude] shape cannot exit 1 at a prompt (run_completion
//      catches and reports).
//    * Environment lookups use libc getenv() directly (never tc_env_get,
//      which would load the config and could tc_fail on a broken file).
//    * tc_count_run's entering-state seed scans files before the window
//      (the Python's complete_users starts the window in "unknown"); the
//      differential logs sit inside the window, so the candidates match.
// ============================================================================

/* POSIX/glibc feature macros before ANY system header (tc_platform.h pulls
   in <time.h>): clock_gettime needs _POSIX_C_SOURCE, readdir's d_type and
   st_mtim need _DEFAULT_SOURCE (config.c / core.c pattern). */
#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE 1
#endif

#include "tc_platform.h"
#include "../third_party/tomlc99/toml.h"

#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>

#include "tc_manual.inc"
#include "tc_fish.inc"

/* The resolved listing the counting pass used (core.c exposes it; the asm
   port's tc_dump reads the same structure from its tc_listing global). */
extern tc_listing tc_core_listing;

// ----------------------------------------------------------------------------
// Constants — mirrors the asm module (tc_misc.S).
// ----------------------------------------------------------------------------
enum {
    MISC_PATH_SZ     = 2048,   /* path buffers: logs root, channel dir, config */
    MISC_MSG_SZ      = 4096,   /* error-message composition buffer */
    MISC_ESC_SZ      = 8192,   /* escaped stderr report buffer */
    MISC_ERRBUF_SZ   = 128,    /* toml_parse_file error buffer */
    MISC_VALUE_SZ    = 512,    /* one TOML value / split token scratch */
    MISC_GROUPS_MAX  = 64,     /* [exclude] group cap (config.c's EX_GROUP_MAX) */
    MISC_LISTING_INIT = 64     /* dated-log listing initial capacity */
};

// ----------------------------------------------------------------------------
// Name list — a deduped, sortable, printable list of NUL-terminated strings
// (the asm port's misc_names arena, as a growing array).
// ----------------------------------------------------------------------------
typedef struct misc_names {
    char **items;
    size_t count;
    size_t cap;
} misc_names;

// ----------------------------------------------------------------------------
// Parsed [exclude] table (Python config_exclusions): groups, always-listed
// group names, and the flat login list.
// ----------------------------------------------------------------------------
typedef struct misc_group {
    char *name;                /* the config key, as written (not lowercased) */
    misc_names members;        /* lowercased member logins */
} misc_group;

typedef struct misc_excl {
    misc_names groups;         /* group names (complete_groups output) */
    misc_group group_recs[MISC_GROUPS_MAX];
    size_t group_count;
    misc_names always;         /* always-listed group names (raw) */
    misc_names flat;           /* flat logins (lowercased) */
} misc_excl;

// ----------------------------------------------------------------------------
// One dated log entry (Python log_files): the parsed date plus the filename,
// so the sort is (date, name) exactly like the Python's.
// ----------------------------------------------------------------------------
typedef struct misc_log_entry {
    int64_t ymd;
    char name[64];
} misc_log_entry;

// ----------------------------------------------------------------------------
// Module session — passed explicitly through the completion helpers (the C
// port keeps no hidden mutable globals).
// ----------------------------------------------------------------------------
typedef struct misc_state {
    const tc_opts *opts;
    toml_table_t *config;              /* parsed config table, or NULL */
    char config_path[MISC_PATH_SZ];    /* expanded config path */
    char config_where[MISC_PATH_SZ];   /* shorten_path(config_path) */
    char logs_root[MISC_PATH_SZ];      /* expanded logs root ("None" when empty) */
    char channel_dir[MISC_PATH_SZ];    /* <logs_root>/<channel dir name> */
    char channel_name[TC_CHANNEL_SZ];
    misc_names names;                  /* the candidate output list */
    misc_excl excl;
    char msg[MISC_MSG_SZ];             /* error-message composition scratch */
    char esc[MISC_ESC_SZ];             /* escaped stderr report buffer */
} misc_state;

// ----------------------------------------------------------------------------
// Small shared helpers.
// ----------------------------------------------------------------------------
static int misc_is_ws(unsigned char c) {
    return c == ' ' || c == '\t' || c == '\n' || c == '\r'
        || c == '\v' || c == '\f';
}

static int misc_is_split_sep(unsigned char c) {
    return c == ',' || misc_is_ws(c);
}

static unsigned char misc_lower_byte(unsigned char c) {
    return (c >= 'A' && c <= 'Z') ? (unsigned char)(c + 32) : c;
}

static char *misc_strdup(const char *s) {
    size_t len = strlen(s);
    char *d = malloc(len + 1);
    if (d == NULL) {
        tc_fail("out of memory");
    }
    memcpy(d, s, len + 1);
    return d;
}

/* Bounded append with automatic remaining-capacity tracking; the cursor ends
   AT the NUL so the next append overwrites it (tc_cat_cstr_cap semantics). */
static char *misc_cat(char *m, char *end, const char *s) {
    return tc_cat_cstr_cap(m, s, (size_t)(end - m));
}

static void misc_names_init(misc_names *ns) {
    memset(ns, 0, sizeof(*ns));
}

/* Add a name (dedup by exact string — Python set/dict-key semantics).
   Returns 0 added, 1 duplicate. */
static int misc_names_add(misc_names *ns, const char *name) {
    size_t i;
    for (i = 0; i < ns->count; i++) {
        if (strcmp(ns->items[i], name) == 0) {
            return 1;
        }
    }
    if (ns->count >= ns->cap) {
        size_t new_cap = ns->cap == 0 ? 32 : ns->cap * 2;
        char **ni = realloc(ns->items, new_cap * sizeof(char *));
        if (ni == NULL) {
            tc_fail("out of memory");
        }
        ns->items = ni;
        ns->cap = new_cap;
    }
    ns->items[ns->count++] = misc_strdup(name);
    return 0;
}

/* Remove every matching entry (Python dict pop). */
static void misc_names_remove(misc_names *ns, const char *name) {
    size_t i = 0;
    while (i < ns->count) {
        if (strcmp(ns->items[i], name) == 0) {
            free(ns->items[i]);
            memmove(&ns->items[i], &ns->items[i + 1],
                    (ns->count - i - 1) * sizeof(char *));
            ns->count--;
        } else {
            i++;
        }
    }
}

static int misc_names_cmp(const void *a, const void *b) {
    return strcmp(*(const char *const *)a, *(const char *const *)b);
}

static void misc_names_sort(misc_names *ns) {
    qsort(ns->items, ns->count, sizeof(char *), misc_names_cmp);
}

static void misc_names_print(const misc_names *ns) {
    size_t i;
    for (i = 0; i < ns->count; i++) {
        tc_puts(ns->items[i]);
        tc_puts("\n");
    }
}

static void misc_names_free(misc_names *ns) {
    size_t i;
    for (i = 0; i < ns->count; i++) {
        free(ns->items[i]);
    }
    free(ns->items);
    memset(ns, 0, sizeof(*ns));
}

static void misc_excl_init(misc_excl *ex) {
    memset(ex, 0, sizeof(*ex));
    misc_names_init(&ex->groups);
    misc_names_init(&ex->always);
    misc_names_init(&ex->flat);
}

static void misc_excl_free(misc_excl *ex) {
    size_t i;
    misc_names_free(&ex->groups);
    misc_names_free(&ex->always);
    misc_names_free(&ex->flat);
    for (i = 0; i < ex->group_count; i++) {
        free(ex->group_recs[i].name);
        misc_names_free(&ex->group_recs[i].members);
    }
    ex->group_count = 0;
}

// ----------------------------------------------------------------------------
// Python repr() for the strings the error messages interpolate with {!r}
// (channel names, group names, config values).  Single-quote mode is
// preferred; a string containing a single quote but no double quote is
// wrapped in double quotes; a double quote anywhere forces single-quote mode
// (the asm port's documented repr selection).  Escapes \\ \n \r \t and the
// mode's quote char.  Writes into dst (cap bytes) and returns the cursor at
// the NUL (tc_cat_cstr_cap semantics).
// ----------------------------------------------------------------------------
static char *misc_py_repr(char *dst, size_t cap, const char *text) {
    const char *p;
    char *cur = dst;
    char *end = dst + cap;
    int dq_mode = 0;
    int dq_seen = 0;
    if (cap == 0) {
        return dst;
    }
    for (p = text; *p != '\0'; p++) {
        if (*p == '"') {
            dq_mode = 0;
            dq_seen = 1;
        } else if (*p == '\'' && !dq_seen) {
            dq_mode = 1;
        }
    }
    *cur++ = dq_mode ? '"' : '\'';
    for (p = text; *p != '\0' && cur + 1 < end; p++) {
        unsigned char c = (unsigned char)*p;
        const char *e2 = NULL;
        if (c == '\n') {
            e2 = "\\n";
        } else if (c == '\r') {
            e2 = "\\r";
        } else if (c == '\t') {
            e2 = "\\t";
        } else if (c == '\\') {
            e2 = "\\\\";
        } else if (dq_mode && c == '"') {
            e2 = "\\\"";
        } else if (!dq_mode && c == '\'') {
            e2 = "\\'";
        }
        if (e2 != NULL) {
            size_t n = strlen(e2);
            if (cur + n + 1 >= end) {
                break;
            }
            memcpy(cur, e2, n);
            cur += n;
        } else {
            *cur++ = (char)c;
        }
    }
    if (cur + 1 < end) {
        *cur++ = dq_mode ? '"' : '\'';
    }
    *cur = '\0';
    return cur;
}

// ----------------------------------------------------------------------------
// The quiet failure report — "completion failed: ConfigError('<escaped msg>')"
// on stderr (Python run_completion: print(f"completion failed: {exc!r}",
// file=sys.stderr)).  Completion must never fail loudly at a prompt.
// ----------------------------------------------------------------------------
static void misc_failed(misc_state *st, const char *msg) {
    const char *pre, *suf;
    size_t pre_len, suf_len;
    const char *p;
    char *cur;
    char *end = st->esc + sizeof(st->esc);
    int dq_mode = 0;
    int dq_seen = 0;

    /* quote selection (see misc_py_repr) */
    for (p = msg; *p != '\0'; p++) {
        if (*p == '"') {
            dq_mode = 0;
            dq_seen = 1;
        } else if (*p == '\'' && !dq_seen) {
            dq_mode = 1;
        }
    }
    pre = dq_mode ? "completion failed: ConfigError(\""
                  : "completion failed: ConfigError('";
    suf = dq_mode ? "\")\n" : "')\n";
    pre_len = strlen(pre);
    suf_len = strlen(suf);
    if (pre_len + suf_len + 1 >= sizeof(st->esc)) {
        return;   /* (unreachable: the prefix/suffix are 35/4 bytes) */
    }
    cur = st->esc;
    memcpy(cur, pre, pre_len);
    cur += pre_len;
    for (p = msg; *p != '\0'; p++) {
        unsigned char c = (unsigned char)*p;
        const char *e2 = NULL;
        if (c == '\n') {
            e2 = "\\n";
        } else if (c == '\r') {
            e2 = "\\r";
        } else if (c == '\t') {
            e2 = "\\t";
        } else if (c == '\\') {
            e2 = "\\\\";
        } else if (dq_mode && c == '"') {
            e2 = "\\\"";
        } else if (!dq_mode && c == '\'') {
            e2 = "\\'";
        }
        if (e2 != NULL) {
            size_t n = strlen(e2);
            if ((size_t)(end - cur) <= n + suf_len) {
                break;   /* truncate rather than overflow */
            }
            memcpy(cur, e2, n);
            cur += n;
        } else {
            if ((size_t)(end - cur) <= 1 + suf_len) {
                break;
            }
            *cur++ = (char)c;
        }
    }
    memcpy(cur, suf, suf_len);
    cur += suf_len;
    tc_eputs(st->esc);
    (void)cur;
}

// ----------------------------------------------------------------------------
// Python config_exclusions — the quiet [exclude] parser.  Fills st->excl
// (groups/always/flat), validating the shape exactly like the reference so a
// broken config reports instead of exiting.  Returns 0 ok, 2 = error printed.
// ----------------------------------------------------------------------------
static int misc_group_index(const misc_state *st, const char *name) {
    size_t i;
    for (i = 0; i < st->excl.group_count; i++) {
        if (strcmp(st->excl.group_recs[i].name, name) == 0) {
            return (int)i;
        }
    }
    return -1;
}

/* Python `", ".join(sorted(groups)) or "(none defined)"`. */
static char *misc_cat_sorted_groups(const misc_state *st, char *m, char *end) {
    misc_names sorted;
    size_t i;
    misc_names_init(&sorted);
    for (i = 0; i < st->excl.group_count; i++) {
        misc_names_add(&sorted, st->excl.group_recs[i].name);
    }
    misc_names_sort(&sorted);
    if (sorted.count == 0) {
        m = misc_cat(m, end, "(none defined)");
    } else {
        for (i = 0; i < sorted.count; i++) {
            if (i > 0) {
                m = misc_cat(m, end, ", ");
            }
            m = misc_cat(m, end, sorted.items[i]);
        }
    }
    misc_names_free(&sorted);
    return m;
}

/* A TOML raw value -> NUL-terminated string (strings unquoted, other raws
   as-is — Python str(value) for the common cases). */
static void misc_toml_value_to_string(const char *raw, char *dst, size_t cap) {
    if (raw[0] == '"' || raw[0] == '\'') {
        char *unquoted = NULL;
        if (toml_rtos(raw, &unquoted) == 0 && unquoted != NULL) {
            tc_copy_str_cap(dst, unquoted, cap);
            free(unquoted);
            return;
        }
        dst[0] = '\0';
        return;
    }
    tc_copy_str_cap(dst, raw, cap);
}

/* Python split_names over a TOML array's stringified elements: each element
   is str().strip().lower(), empties dropped — elements are NOT re-split on
   commas/spaces (the string form below is the one that splits). */
static void misc_cfg_members(toml_array_t *arr, misc_names *out) {
    int n = toml_array_nelem(arr);
    int i;
    for (i = 0; i < n; i++) {
        const char *raw = toml_raw_at(arr, i);
        char val[MISC_VALUE_SZ];
        char stripped[MISC_VALUE_SZ];
        size_t len;
        size_t lead = 0;
        size_t end;
        size_t out_len;
        size_t j;
        if (raw == NULL) {
            continue;
        }
        misc_toml_value_to_string(raw, val, sizeof(val));
        len = strlen(val);
        while (lead < len && misc_is_ws((unsigned char)val[lead])) {
            lead++;
        }
        end = len;
        while (end > lead && misc_is_ws((unsigned char)val[end - 1])) {
            end--;
        }
        out_len = end - lead;
        if (out_len >= sizeof(stripped)) {
            out_len = sizeof(stripped) - 1;
        }
        for (j = 0; j < out_len; j++) {
            stripped[j] = (char)misc_lower_byte((unsigned char)val[lead + j]);
        }
        stripped[out_len] = '\0';
        if (out_len > 0) {
            misc_names_add(out, stripped);
        }
    }
}

/* Python split_names over a string (re.split(r"[,\s]+", s), then strip +
   lower, empties dropped).  Each token is added to ns. */
static void misc_split_add(misc_names *ns, const char *value) {
    const char *p = value;
    for (;;) {
        const char *start;
        size_t len;
        size_t i;
        char tok[MISC_VALUE_SZ];
        while (*p != '\0' && misc_is_split_sep((unsigned char)*p)) {
            p++;
        }
        if (*p == '\0') {
            return;
        }
        start = p;
        while (*p != '\0' && !misc_is_split_sep((unsigned char)*p)) {
            p++;
        }
        len = (size_t)(p - start);
        if (len >= sizeof(tok)) {
            len = sizeof(tok) - 1;
        }
        for (i = 0; i < len; i++) {
            tok[i] = (char)misc_lower_byte((unsigned char)start[i]);
        }
        tok[len] = '\0';
        misc_names_add(ns, tok);
    }
}

static void misc_split_remove(misc_names *ns, const char *value) {
    const char *p = value;
    for (;;) {
        const char *start;
        size_t len;
        char tok[MISC_VALUE_SZ];
        while (*p != '\0' && misc_is_split_sep((unsigned char)*p)) {
            p++;
        }
        if (*p == '\0') {
            return;
        }
        start = p;
        while (*p != '\0' && !misc_is_split_sep((unsigned char)*p)) {
            p++;
        }
        len = (size_t)(p - start);
        if (len >= sizeof(tok)) {
            len = sizeof(tok) - 1;
        }
        memcpy(tok, start, len);
        tok[len] = '\0';
        misc_names_remove(ns, tok);
    }
}

static int misc_cfg_exclusions(misc_state *st) {
    toml_table_t *root = st->config;
    toml_array_t *arr;
    toml_table_t *tab;
    int total;
    int i;
    char *m;
    char *end = st->msg + sizeof(st->msg);

    if (root == NULL) {
        return 0;   /* no config: empty exclusions */
    }
    /* a scalar "exclude" is the shape error (Python: not a list, not a dict) */
    if (toml_raw_in(root, "exclude") != NULL) {
        m = st->msg;
        m = misc_cat(m, end, "`exclude` in ");
        m = misc_cat(m, end, st->config_where);
        m = misc_cat(m, end, " must be a list of logins or a table of groups");
        *m = '\0';
        misc_failed(st, st->msg);
        return 2;
    }
    arr = toml_array_in(root, "exclude");
    if (arr != NULL) {
        /* exclude = [ ... ] -> flat logins */
        misc_cfg_members(arr, &st->excl.flat);
        return 0;
    }
    tab = toml_table_in(root, "exclude");
    if (tab == NULL) {
        return 0;   /* no exclude key */
    }
    total = toml_table_nkval(tab) + toml_table_narr(tab) + toml_table_ntab(tab);
    for (i = 0; i < total; i++) {
        const char *name = toml_key_in(tab, i);
        toml_array_t *members;
        if (name == NULL) {
            continue;
        }
        if (strcmp(name, "always") == 0) {
            continue;
        }
        members = toml_array_in(tab, name);
        if (members == NULL) {
            m = st->msg;
            m = misc_cat(m, end, "[exclude].");
            m = misc_cat(m, end, name);
            m = misc_cat(m, end, " in ");
            m = misc_cat(m, end, st->config_where);
            m = misc_cat(m, end, " must be a list of logins");
            *m = '\0';
            misc_failed(st, st->msg);
            return 2;
        }
        if (st->excl.group_count < MISC_GROUPS_MAX) {
            misc_group *g = &st->excl.group_recs[st->excl.group_count];
            misc_names_init(&g->members);
            g->name = misc_strdup(name);
            misc_names_add(&st->excl.groups, name);
            misc_cfg_members(members, &g->members);
            st->excl.group_count++;
        }
    }
    /* the "always" array of group names */
    if (toml_key_exists(tab, "always")) {
        toml_array_t *always = toml_array_in(tab, "always");
        if (always == NULL) {
            m = st->msg;
            m = misc_cat(m, end, "[exclude].always in ");
            m = misc_cat(m, end, st->config_where);
            m = misc_cat(m, end, " must be a list of group names");
            *m = '\0';
            misc_failed(st, st->msg);
            return 2;
        }
        {
            int n = toml_array_nelem(always);
            for (i = 0; i < n; i++) {
                const char *raw = toml_raw_at(always, i);
                char aname[MISC_VALUE_SZ];
                if (raw == NULL) {
                    continue;
                }
                misc_toml_value_to_string(raw, aname, sizeof(aname));
                if (misc_group_index(st, aname) < 0) {
                    m = st->msg;
                    m = misc_cat(m, end, "[exclude].always in ");
                    m = misc_cat(m, end, st->config_where);
                    m = misc_cat(m, end, " names unknown group ");
                    m = misc_py_repr(m, (size_t)(end - m), aname);
                    m = st->msg + strlen(st->msg);
                    m = misc_cat(m, end, "; defined groups: ");
                    m = misc_cat_sorted_groups(st, m, end);
                    *m = '\0';
                    misc_failed(st, st->msg);
                    return 2;
                }
                misc_names_add(&st->excl.always, aname);
            }
        }
    }
    return 0;
}

// ----------------------------------------------------------------------------
// Config layer (Python load_config_layer + load_config).
//
//  The C tc_cli_parse resolves settings before the config module can see a
//  --config path (config.c's lazy load caches the default-path result first),
//  so this module is where the --config file is actually loaded for a
//  completion.  A config that fails to LOAD (missing explicit path, TOML or
//  I/O error) exits 1 loudly — the documented divergence, shared with the
//  asm port's eager load (the Python reports quietly and exits 0).  Errors
//  AFTER a successful load ([exclude] shape, channel resolution) stay quiet
//  through misc_failed, exactly like run_completion.
// ----------------------------------------------------------------------------
static int misc_config_open(misc_state *st) {
    const tc_opts *opts = st->opts;
    const char *src = NULL;
    int explicit = 0;
    char path[MISC_PATH_SZ];
    char *m;
    char *end;
    struct stat sb;
    FILE *fp;
    toml_table_t *tab;
    char errbuf[MISC_ERRBUF_SZ];
    size_t len;

    if (opts->flags & TC_F_NO_CONFIG) {
        return 0;   /* --no-config -> {} */
    }
    /* explicit = --config or TWITCH_COUNTS_CONFIG */
    if (opts->flags & TC_F_CONFIG_GIVEN) {
        src = opts->config_path;
        explicit = 1;
    } else {
        const char *env = getenv("TWITCH_COUNTS_CONFIG");
        if (env != NULL && env[0] != '\0') {
            src = env;
            explicit = 1;
        }
    }
    if (src != NULL) {
        tc_expanduser(src, path, sizeof(path));
    } else {
        len = tc_default_config_path(path, sizeof(path));
        if (len == 0 || len >= sizeof(path)) {
            path[0] = '\0';
        }
    }
    if (path[0] == '\0') {
        return 0;   /* no default on this platform -> {} */
    }
    tc_copy_str_cap(st->config_path, path, sizeof(st->config_path));
    {
        const char *shortened = tc_shorten_path(path);
        tc_copy_str_cap(st->config_where, shortened, sizeof(st->config_where));
    }
    /* load_config: a missing default path -> {}; a missing explicit one
       raises ConfigError — loudly here (the documented divergence) */
    if (stat(path, &sb) != 0 || !S_ISREG(sb.st_mode)) {
        if (explicit) {
            char msg[MISC_MSG_SZ];
            m = msg;
            end = msg + sizeof(msg);
            m = misc_cat(m, end, "config file not found: ");
            m = misc_cat(m, end, path);
            *m = '\0';
            tc_fail(msg);
        }
        return 0;
    }
    fp = fopen(path, "rb");
    if (fp == NULL) {
        char msg[MISC_MSG_SZ];
        int err = errno;
        m = msg;
        end = msg + sizeof(msg);
        m = misc_cat(m, end, "could not read config ");
        m = misc_cat(m, end, path);
        m = misc_cat(m, end, ": ");
        m = misc_cat(m, end, tc_oserror_text(err));
        m = misc_cat(m, end, ": '");
        m = misc_cat(m, end, path);
        m = misc_cat(m, end, "'");
        *m = '\0';
        tc_fail(msg);
    }
    errbuf[0] = '\0';
    tab = toml_parse_file(fp, errbuf, sizeof(errbuf));
    fclose(fp);
    if (tab == NULL) {
        char msg[MISC_MSG_SZ];
        m = msg;
        end = msg + sizeof(msg);
        m = misc_cat(m, end, "could not read config ");
        m = misc_cat(m, end, path);
        m = misc_cat(m, end, ": ");
        m = misc_cat(m, end, errbuf);
        *m = '\0';
        tc_fail(msg);
    }
    st->config = tab;
    return 0;
}

// ----------------------------------------------------------------------------
// Path helpers.
// ----------------------------------------------------------------------------
/* Python completion_candidates' channel resolve: CLI > env > config.  The C
   tc_cli_parse resolves the settings before the config module can see a
   --config path (s_opts is registered by tc_aliases_apply afterwards), so a
   channel that lives in a --config file never reaches opts->channel.  The
   completion module therefore re-resolves from its own parsed table: the
   CLI/env values tc_cli_parse already resolved are authoritative, and
   TC_SRC_CONFIG / TC_SRC_DEFAULT fall through to the config layer. */
static const char *misc_resolve_channel(misc_state *st, char *dst, size_t cap) {
    const tc_opts *opts = st->opts;
    enum tc_source src = opts->src[TC_SET_CHANNEL];

    if (src != TC_SRC_CONFIG && src != TC_SRC_DEFAULT) {
        /* CLI / env / alias: tc_cli_parse's resolved value is authoritative */
        tc_copy_str_cap(dst, opts->channel, cap);
        return dst;
    }
    if (st->config != NULL) {
        const char *raw = toml_raw_in(st->config, "channel");
        if (raw != NULL) {
            misc_toml_value_to_string(raw, dst, cap);
            if (dst[0] != '\0') {
                return dst;
            }
        }
    }
    if (src == TC_SRC_CONFIG) {
        /* no --config, same default-path file tc_cli_parse loaded */
        tc_copy_str_cap(dst, opts->channel, cap);
        return dst;
    }
    dst[0] = '\0';
    return dst;
}

/* Python: os.path.expanduser(str(logs_dir.value)) — resolved the same way
   completion_candidates resolves logs-dir (CLI > env > config > platform
   default), with "None" for the Linux platform stub's absent default. */
static void misc_expand_root(misc_state *st) {
    const tc_opts *opts = st->opts;
    enum tc_source src = opts->src[TC_SET_LOGS_DIR];

    if (src != TC_SRC_CONFIG && src != TC_SRC_DEFAULT_BUILTIN) {
        /* CLI / env: tc_cli_parse's resolved value is authoritative */
        tc_expanduser(opts->logs_dir, st->logs_root, sizeof(st->logs_root));
        return;
    }
    if (src == TC_SRC_CONFIG) {
        /* config layer: the completion's own table honors --config */
        if (st->config != NULL) {
            const char *raw = toml_raw_in(st->config, "logs_dir");
            if (raw != NULL) {
                char val[MISC_PATH_SZ];
                misc_toml_value_to_string(raw, val, sizeof(val));
                if (val[0] != '\0') {
                    tc_expanduser(val, st->logs_root, sizeof(st->logs_root));
                    return;
                }
            }
        }
        /* no config logs_dir: the platform default tc_cli_parse filled */
        tc_expanduser(opts->logs_dir, st->logs_root, sizeof(st->logs_root));
        return;
    }
    /* TC_SRC_DEFAULT_BUILTIN: the platform default (empty on Linux) */
    if (opts->logs_dir[0] != '\0') {
        tc_expanduser(opts->logs_dir, st->logs_root, sizeof(st->logs_root));
    } else {
        tc_copy_str_cap(st->logs_root, "None", sizeof(st->logs_root));
    }
}

static int misc_is_dir(const char *path) {
    struct stat sb;
    return stat(path, &sb) == 0 && S_ISDIR(sb.st_mode);
}

/* Every subdirectory of path (d_type DT_DIR, skipping "." and ".."), added
   and sorted.  Returns 1 when the directory could be opened, 0 otherwise. */
static int misc_list_dirs(const char *path, misc_names *dirs) {
    DIR *d = opendir(path);
    struct dirent *de;
    if (d == NULL) {
        return 0;
    }
    while ((de = readdir(d)) != NULL) {
        if (de->d_type != DT_DIR) {
            continue;
        }
        if (strcmp(de->d_name, ".") == 0 || strcmp(de->d_name, "..") == 0) {
            continue;
        }
        misc_names_add(dirs, de->d_name);
    }
    closedir(d);
    misc_names_sort(dirs);
    return 1;
}

static void misc_lowercase_into(const char *src, char *dst, size_t cap) {
    size_t i = 0;
    for (;;) {
        unsigned char c;
        if (i + 1 >= cap) {
            dst[i] = '\0';
            return;
        }
        c = (unsigned char)src[i];
        if (c >= 'A' && c <= 'Z') {
            c = (unsigned char)(c + 32);
        }
        dst[i] = (char)c;
        if (c == '\0') {
            return;
        }
        i++;
    }
}

/* aliases.get(key, key): the config's [aliases] value for the channel, or
   the channel itself (Python completion_candidates). */
static const char *misc_aliased_channel(const misc_state *st, const char *key,
                                        char *dst, size_t cap) {
    toml_table_t *aliases;
    const char *raw;
    if (st->config == NULL) {
        return key;
    }
    aliases = toml_table_in(st->config, "aliases");
    if (aliases == NULL) {
        return key;
    }
    raw = toml_raw_in(aliases, key);
    if (raw == NULL) {
        return key;
    }
    misc_toml_value_to_string(raw, dst, cap);
    return dst;
}

// ----------------------------------------------------------------------------
// Channel resolution (Python resolve_channel_dir) — the quiet version: a
// missing logs root / channel dir reports a ConfigError instead of exiting.
// Returns 0 ok (channel_dir/channel_name filled), 1 no channel (empty
// output), 2 error printed.
// ----------------------------------------------------------------------------
static int misc_require_channel(misc_state *st) {
    char resolved[TC_CHANNEL_SZ];
    const char *channel;
    char alias_buf[MISC_PATH_SZ];
    const char *aliased;
    char lower[TC_CHANNEL_SZ];
    misc_names dirs;
    size_t i;
    char *m;
    char *end;

    channel = misc_resolve_channel(st, resolved, sizeof(resolved));
    if (channel[0] == '\0') {
        return 1;   /* Python: if not channel: return [] */
    }
    misc_expand_root(st);
    if (!misc_is_dir(st->logs_root)) {
        m = st->msg;
        end = st->msg + sizeof(st->msg);
        m = misc_cat(m, end, "logs directory not found: ");
        m = misc_cat(m, end, st->logs_root);
        *m = '\0';
        misc_failed(st, st->msg);
        return 2;
    }
    misc_names_init(&dirs);
    misc_list_dirs(st->logs_root, &dirs);
    aliased = misc_aliased_channel(st, channel, alias_buf,
                                   sizeof(alias_buf));
    misc_lowercase_into(aliased, lower, sizeof(lower));
    for (i = 0; i < dirs.count; i++) {
        if (tc_ascii_casecmp(dirs.items[i], lower) == 0) {
            snprintf(st->channel_dir, sizeof(st->channel_dir), "%s/%s",
                     st->logs_root, dirs.items[i]);
            tc_copy_str_cap(st->channel_name, dirs.items[i],
                            sizeof(st->channel_name));
            misc_names_free(&dirs);
            return 0;
        }
    }
    /* "no logs for channel '<ch>' in <root>\navailable: <join|(none)>" */
    m = st->msg;
    end = st->msg + sizeof(st->msg);
    m = misc_cat(m, end, "no logs for channel ");
    m = misc_py_repr(m, (size_t)(end - m), aliased);
    m = st->msg + strlen(st->msg);
    m = misc_cat(m, end, " in ");
    m = misc_cat(m, end, st->logs_root);
    m = misc_cat(m, end, "\navailable: ");
    if (dirs.count == 0) {
        m = misc_cat(m, end, "(none)");
    } else {
        for (i = 0; i < dirs.count; i++) {
            if (i > 0) {
                m = misc_cat(m, end, ", ");
            }
            m = misc_cat(m, end, dirs.items[i]);
        }
    }
    *m = '\0';
    misc_names_free(&dirs);
    misc_failed(st, st->msg);
    return 2;
}

// ----------------------------------------------------------------------------
// The dated-log listing (Python log_files): every name shaped
// "<anything>-YYYY-MM-DD.log" with a real calendar date, sorted ascending.
// Built here with core.c's tc_parse_log_filename_n so the FILENAME_RE
// filtering, date validation and sort are the differential-tested ones.
// Returns 0 ok, 2 = error printed (the channel dir cannot be opened).
// ----------------------------------------------------------------------------
static int misc_log_cmp(const void *a, const void *b) {
    const misc_log_entry *ea = a;
    const misc_log_entry *eb = b;
    if (ea->ymd < eb->ymd) {
        return -1;
    }
    if (ea->ymd > eb->ymd) {
        return 1;
    }
    return strcmp(ea->name, eb->name);
}

/* The Python exception class for an errno (mirrors core.c's map) — used for
   the quiet OSError repr when a listing cannot be opened. */
static const char *misc_errno_exc(int err) {
    switch (err) {
    case EPERM:
    case EACCES:
        return "PermissionError";
    case ENOENT:
        return "FileNotFoundError";
    case EISDIR:
        return "IsADirectoryError";
    case ENOTDIR:
        return "NotADirectoryError";
    case EEXIST:
        return "FileExistsError";
    case EINTR:
        return "InterruptedError";
    case EPIPE:
        return "BrokenPipeError";
    default:
        return "OSError";
    }
}

static int misc_listing_build(misc_state *st, misc_log_entry **out,
                              size_t *count_out) {
    DIR *d = opendir(st->channel_dir);
    struct dirent *de;
    size_t count = 0;
    size_t cap = 0;
    misc_log_entry *entries = NULL;
    char *m;
    char *end;

    if (d == NULL) {
        /* The channel dir was verified a moment ago; a failure here is a
           race.  The Python raises an OSError that run_completion reports
           quietly as its repr: ExcClass(errno, 'strerror'). */
        int err = errno;
        m = st->msg;
        end = st->msg + sizeof(st->msg);
        m = misc_cat(m, end, misc_errno_exc(err));
        m = misc_cat(m, end, "(");
        m = tc_fmt_u64(m, (uint64_t)err);
        m = misc_cat(m, end, ", '");
        m = misc_cat(m, end, strerror(err));
        m = misc_cat(m, end, "')");
        *m = '\0';
        misc_failed(st, st->msg);
        *out = NULL;
        *count_out = 0;
        return 2;
    }
    while ((de = readdir(d)) != NULL) {
        size_t len = strlen(de->d_name);
        int64_t ymd = tc_parse_log_filename_n(de->d_name, len);
        if (ymd == 0) {
            continue;
        }
        if (count >= cap) {
            size_t new_cap = cap == 0 ? MISC_LISTING_INIT : cap * 2;
            misc_log_entry *ne = realloc(entries,
                                         new_cap * sizeof(*ne));
            if (ne == NULL) {
                closedir(d);
                free(entries);
                tc_fail("out of memory");
            }
            entries = ne;
            cap = new_cap;
        }
        entries[count].ymd = ymd;
        tc_copy_str_cap(entries[count].name, de->d_name,
                        sizeof(entries[count].name));
        count++;
    }
    closedir(d);
    qsort(entries, count, sizeof(misc_log_entry), misc_log_cmp);
    *out = entries;
    *count_out = count;
    return 0;
}

// ----------------------------------------------------------------------------
// Date/week formatting.
// ----------------------------------------------------------------------------
/* "YYYY-MM-DD" into dst (11 bytes + NUL). */
static void misc_fmt_ymd(int64_t ymd, char *dst) {
    int y, mo, d;
    tc_ymd_split(ymd, &y, &mo, &d);
    dst = tc_fmt4(dst, (uint64_t)y);
    *dst++ = '-';
    dst = tc_fmt2(dst, (uint64_t)mo);
    *dst++ = '-';
    dst = tc_fmt2(dst, (uint64_t)d);
    *dst = '\0';
}

/* "YYYY-WNN" into dst (11 bytes + NUL). */
static void misc_fmt_week(int iso_year, int iso_week, char *dst) {
    dst = tc_fmt4(dst, (uint64_t)iso_year);
    *dst++ = '-';
    *dst++ = 'W';
    dst = tc_fmt2(dst, (uint64_t)iso_week);
    *dst = '\0';
}

/* ISO-8601 week of a packed YYYYMMDD date (the asm port's algorithm,
   verified against Python's datetime.isocalendar for years 1..9999). */
static void misc_iso_week(int64_t ymd, int *iso_year, int *iso_week) {
    int y, m, d;
    int64_t epoch;
    int iso_wd;
    int64_t thu;
    int ty, tm, td;
    int64_t jan4;
    int jw;
    int64_t week1;
    int64_t week;

    tc_ymd_split(ymd, &y, &m, &d);
    epoch = tc_days_from_civil(y, m, d);
    /* iso weekday, Mon=1 (1970-01-01 is a Thursday) */
    iso_wd = (int)(((epoch + 3) % 7 + 7) % 7 + 1);
    thu = epoch + (4 - iso_wd);
    tc_civil_from_days(thu, &ty, &tm, &td);
    jan4 = tc_days_from_civil(ty, 1, 4);
    jw = (int)(((jan4 + 3) % 7 + 7) % 7 + 1);
    week1 = jan4 - (jw - 1);
    week = (epoch - week1) / 7 + 1;
    *iso_year = ty;
    *iso_week = (int)week;
}

// ----------------------------------------------------------------------------
// Handlers.
// ----------------------------------------------------------------------------

/* complete_channels: sorted(alias keys + logs-root subdirs). */
static void misc_complete_channels(misc_state *st) {
    toml_table_t *aliases;
    int total;
    int i;

    if (st->config != NULL) {
        aliases = toml_table_in(st->config, "aliases");
        if (aliases != NULL) {
            total = toml_table_nkval(aliases) + toml_table_narr(aliases)
                + toml_table_ntab(aliases);
            for (i = 0; i < total; i++) {
                const char *key = toml_key_in(aliases, i);
                if (key != NULL) {
                    misc_names_add(&st->names, key);
                }
            }
        }
    }
    /* logs-root subdirectories (Python: if os.path.isdir(logs_root)) */
    misc_expand_root(st);
    if (misc_is_dir(st->logs_root)) {
        misc_list_dirs(st->logs_root, &st->names);
    }
    misc_names_sort(&st->names);
    misc_names_print(&st->names);
}

/* complete_groups: sorted [exclude] group names (config_exclusions). */
static void misc_complete_groups(misc_state *st) {
    if (misc_cfg_exclusions(st) != 0) {
        return;   /* error printed */
    }
    misc_names_sort(&st->excl.groups);
    misc_names_print(&st->excl.groups);
}

/* complete_dates: every dated log file's date, ascending, one per line. */
static void misc_complete_dates(misc_state *st) {
    misc_log_entry *entries = NULL;
    size_t count = 0;
    size_t i;
    char buf[16];

    if (misc_listing_build(st, &entries, &count) != 0) {
        free(entries);
        return;
    }
    for (i = 0; i < count; i++) {
        misc_fmt_ymd(entries[i].ymd, buf);
        tc_puts(buf);
        tc_puts("\n");
    }
    free(entries);
}

/* complete_weeks: ISO weeks of the dated logs, deduped, in date order
   (sorting the dedup list is a no-op for well-formed ISO weeks — the asm
   port sorts; the Python relies on the date order). */
static void misc_complete_weeks(misc_state *st) {
    misc_log_entry *entries = NULL;
    size_t count = 0;
    size_t i;
    char buf[16];

    if (misc_listing_build(st, &entries, &count) != 0) {
        free(entries);
        return;
    }
    for (i = 0; i < count; i++) {
        int year, week;
        misc_iso_week(entries[i].ymd, &year, &week);
        misc_fmt_week(year, week, buf);
        misc_names_add(&st->names, buf);
    }
    free(entries);
    misc_names_sort(&st->names);
    misc_names_print(&st->names);
}

/* complete_periods: weeks then dates (Python: weeks + dates). */
static void misc_complete_periods(misc_state *st) {
    misc_log_entry *entries = NULL;
    size_t count = 0;
    size_t i;
    char buf[16];

    if (misc_listing_build(st, &entries, &count) != 0) {
        free(entries);
        return;
    }
    for (i = 0; i < count; i++) {
        int year, week;
        misc_iso_week(entries[i].ymd, &year, &week);
        misc_fmt_week(year, week, buf);
        misc_names_add(&st->names, buf);
    }
    misc_names_print(&st->names);   /* weeks: date order, not re-sorted */
    for (i = 0; i < count; i++) {
        misc_fmt_ymd(entries[i].ymd, buf);
        tc_puts(buf);
        tc_puts("\n");
    }
    free(entries);
}

/* Stable sort descending by value, ties keeping the input order (Python
   Counter.most_common: count desc, first-seen ties). */
static void misc_sort_by_value(int64_t *idx, int64_t *vals, int64_t n) {
    int64_t i, j;
    if (n < 2) {
        return;
    }
    for (i = 1; i < n; i++) {
        int64_t key_idx = idx[i];
        int64_t key_val = vals[i];
        j = i - 1;
        while (j >= 0 && vals[j] < key_val) {
            idx[j + 1] = idx[j];
            vals[j + 1] = vals[j];
            j--;
        }
        idx[j + 1] = key_idx;
        vals[j + 1] = key_val;
    }
}

static int misc_in_users(const tc_users *users, const char *login) {
    int64_t i;
    for (i = 0; i < users->count; i++) {
        if (strcmp(users->entries[i].login, login) == 0) {
            return 1;
        }
    }
    return 0;
}

/* complete_users: a 7-day counting pass, then sorted config-known.  The
   window is end = now UTC, begin = end - 7 days (documented divergence: the
   Python uses local time). */
static void misc_complete_users(misc_state *st) {
    tc_window window;
    tc_users users;
    tc_tally tally;
    tc_opts copy;
    int64_t end_ymd, end_sod;
    int64_t begin_ymd, begin_sod;
    int64_t end_epoch;
    int64_t *idx = NULL;
    int64_t *vals = NULL;
    int64_t n;
    int64_t i;
    size_t g, j;

    /* the Python's config_exclusions runs inside complete_users — validate
       the [exclude] shape quietly before the count */
    if (misc_cfg_exclusions(st) != 0) {
        return;   /* error printed */
    }

    tc_misc_now_utc(&end_ymd, &end_sod);
    end_epoch = tc_ymd_sod_to_epoch(end_ymd, end_sod);
    tc_epoch_to_ymd_sod(end_epoch - 7 * TC_SECS_PER_DAY, &begin_ymd,
                        &begin_sod);
    memset(&window, 0, sizeof(window));
    window.begin_ymd = begin_ymd;
    window.begin_sod = begin_sod;
    window.end_ymd = end_ymd;
    window.end_sod = end_sod;
    window.kind = TC_WIN_BEGIN;
    window.threshold = 1;
    window.state_filter = TC_ST_NONE;

    /* The Python counts EVERYONE (no exclusion filtering) and never
       validates --exclude-group / --no-exclude for the users kind, so the
       counting pass gets a sanitized copy: exclusions neutralized and the
       channel/logs-root resolved (the alias was already applied). */
    copy = *st->opts;
    copy.flags |= TC_F_NO_EXCLUDE;
    copy.flags &= ~(TC_F_EXCL_GIVEN | TC_F_EXCL_GROUP_GIVEN
                    | TC_F_EXCLUDE_BCAST | TC_F_INCL_GIVEN);
    copy.excl_count = 0;
    copy.excl_group_count = 0;
    copy.incl_count = 0;
    copy.excl_bcast_val = 0;
    tc_copy_str_cap(copy.channel, st->channel_name, sizeof(copy.channel));
    tc_copy_str_cap(copy.logs_dir, st->logs_root, sizeof(copy.logs_dir));

    memset(&users, 0, sizeof(users));
    memset(&tally, 0, sizeof(tally));
    tally.users = &users;
    if (tc_count_run(&copy, &window, &tally) != TC_EXIT_OK) {
        /* tc_build_exclusions cannot fail on the sanitized copy and the
           channel was already resolved, so this is unreachable. */
        free(users.entries);
        return;
    }

    /* most_common() order: stable sort of (index, total) by total desc */
    n = users.count;
    if (n > 0) {
        idx = malloc((size_t)n * sizeof(int64_t));
        vals = malloc((size_t)n * sizeof(int64_t));
        if (idx == NULL || vals == NULL) {
            tc_fail("out of memory");
        }
    }
    for (i = 0; i < n; i++) {
        idx[i] = i;
        vals[i] = tc_user_count(&users.entries[i]);
    }
    misc_sort_by_value(idx, vals, n);
    for (i = 0; i < n; i++) {
        tc_puts(users.entries[idx[i]].login);
        tc_puts("\n");
    }
    free(idx);
    free(vals);

    /* sorted(known - counts): flat exclusions + every group's members */
    {
        misc_names known;
        misc_names_init(&known);
        for (j = 0; j < st->excl.flat.count; j++) {
            misc_names_add(&known, st->excl.flat.items[j]);
        }
        for (g = 0; g < st->excl.group_count; g++) {
            const misc_group *gr = &st->excl.group_recs[g];
            for (j = 0; j < gr->members.count; j++) {
                misc_names_add(&known, gr->members.items[j]);
            }
        }
        misc_names_sort(&known);
        for (j = 0; j < known.count; j++) {
            if (misc_in_users(&users, known.items[j])) {
                continue;
            }
            tc_puts(known.items[j]);
            tc_puts("\n");
        }
        misc_names_free(&known);
    }

    free(users.entries);
    free(tc_core_listing.entries);
    tc_core_listing.entries = NULL;
    tc_core_listing.count = 0;
    tc_core_listing.cap = 0;
}

/* Add every member of the named group to st->names; 0 found, 1 unknown. */
static int misc_add_group_members(misc_state *st, const char *name) {
    int gi = misc_group_index(st, name);
    size_t j;
    if (gi < 0) {
        return 1;
    }
    for (j = 0; j < st->excl.group_recs[gi].members.count; j++) {
        misc_names_add(&st->names, st->excl.group_recs[gi].members.items[j]);
    }
    return 0;
}

/* Python resolve("exclude-broadcaster", ...) + convert(parse_bool): CLI
   wins, then env TWITCH_EXCLUDE_BROADCASTER, then config
   exclude_broadcaster, else False.  Returns 1 yes / 0 no / -1 error printed. */
static int misc_wants_broadcaster(misc_state *st) {
    const tc_opts *opts = st->opts;
    const char *env;
    int ok = 1;
    int value;
    char *m;
    char *end;

    if (opts->flags & TC_F_EXCLUDE_BCAST) {
        return opts->excl_bcast_val != 0;
    }
    env = getenv("TWITCH_EXCLUDE_BROADCASTER");
    if (env != NULL && env[0] != '\0') {
        value = tc_parse_bool(env, &ok);
        if (!ok) {
            m = st->msg;
            end = st->msg + sizeof(st->msg);
            m = misc_cat(m, end, "--exclude-broadcaster (from env "
                                 "TWITCH_EXCLUDE_BROADCASTER): expected true "
                                 "or false, got ");
            m = misc_py_repr(m, (size_t)(end - m), env);
            m = st->msg + strlen(st->msg);
            *m = '\0';
            misc_failed(st, st->msg);
            return -1;
        }
        return value;
    }
    if (st->config != NULL) {
        const char *raw = toml_raw_in(st->config, "exclude_broadcaster");
        if (raw != NULL) {
            char val[MISC_VALUE_SZ];
            misc_toml_value_to_string(raw, val, sizeof(val));
            value = tc_parse_bool(val, &ok);
            if (!ok) {
                m = st->msg;
                end = st->msg + sizeof(st->msg);
                m = misc_cat(m, end, "--exclude-broadcaster (from config): "
                                     "expected true or false, got ");
                m = misc_py_repr(m, (size_t)(end - m), val);
                m = st->msg + strlen(st->msg);
                *m = '\0';
                misc_failed(st, st->msg);
                return -1;
            }
            return value;
        }
    }
    return 0;
}

/* complete_includes: sorted merged exclusion logins (Python build_exclusions
   + exclusion_layers + the --include subtraction). */
static void misc_complete_includes(misc_state *st) {
    const tc_opts *opts = st->opts;
    const char *conf[4];
    int n = 0;
    int i;
    int wb;
    char *m;
    char *end;

    /* Python build_exclusions checks --no-exclude conflicts FIRST */
    if (opts->flags & TC_F_NO_EXCLUDE) {
        if (opts->flags & TC_F_EXCL_GIVEN) {
            conf[n++] = "--exclude";
        }
        if (opts->flags & TC_F_EXCL_GROUP_GIVEN) {
            conf[n++] = "--exclude-group";
        }
        if (opts->flags & TC_F_EXCLUDE_BCAST) {
            conf[n++] = "--exclude-broadcaster";
        }
        if (opts->flags & TC_F_INCL_GIVEN) {
            conf[n++] = "--include";
        }
        if (n > 0) {
            m = st->msg;
            end = st->msg + sizeof(st->msg);
            m = misc_cat(m, end, "--no-exclude cannot be combined with ");
            for (i = 0; i < n; i++) {
                if (i > 0) {
                    m = misc_cat(m, end, ", ");
                }
                m = misc_cat(m, end, conf[i]);
            }
            *m = '\0';
            misc_failed(st, st->msg);
            return;
        }
        return;   /* --no-exclude with nothing conflicting: empty candidates */
    }

    /* config exclusions (quiet) */
    if (misc_cfg_exclusions(st) != 0) {
        return;
    }
    /* layer 1: config flat */
    for (i = 0; i < (int)st->excl.flat.count; i++) {
        misc_names_add(&st->names, st->excl.flat.items[i]);
    }
    /* layer 2: config always:<name> groups (unknown always names were
       rejected by config_exclusions above) */
    for (i = 0; i < (int)st->excl.always.count; i++) {
        misc_add_group_members(st, st->excl.always.items[i]);
    }
    /* layer 3: --exclude-group NAME (validated like the Python) */
    for (i = 0; i < opts->excl_group_count; i++) {
        if (misc_add_group_members(st, opts->excl_group_list[i]) == 0) {
            continue;
        }
        m = st->msg;
        end = st->msg + sizeof(st->msg);
        m = misc_cat(m, end, "unknown exclude group ");
        m = misc_py_repr(m, (size_t)(end - m), opts->excl_group_list[i]);
        m = st->msg + strlen(st->msg);
        m = misc_cat(m, end, "; defined groups: ");
        m = misc_cat_sorted_groups(st, m, end);
        *m = '\0';
        misc_failed(st, st->msg);
        return;
    }
    /* layer 4: env TWITCH_EXCLUDE */
    {
        const char *env = getenv("TWITCH_EXCLUDE");
        if (env != NULL && env[0] != '\0') {
            misc_split_add(&st->names, env);
        }
    }
    /* layer 5: --exclude LOGIN[,LOGIN...] */
    for (i = 0; i < opts->excl_count; i++) {
        misc_split_add(&st->names, opts->excl_list[i]);
    }
    /* layer 6: --exclude-broadcaster (login = lowercased channel) */
    wb = misc_wants_broadcaster(st);
    if (wb < 0) {
        return;   /* error printed */
    }
    if (wb) {
        char lower[TC_CHANNEL_SZ];
        misc_lowercase_into(st->channel_name, lower, sizeof(lower));
        misc_names_add(&st->names, lower);
    }
    /* --include subtraction */
    for (i = 0; i < opts->incl_count; i++) {
        misc_split_remove(&st->names, opts->incl_list[i]);
    }
    misc_names_sort(&st->names);
    misc_names_print(&st->names);
}

static void misc_state_free(misc_state *st) {
    if (st->config != NULL) {
        toml_free(st->config);
        st->config = NULL;
    }
    misc_names_free(&st->names);
    misc_excl_free(&st->excl);
}

// ============================================================================
// Exported entry points.
// ============================================================================

/* --manual: print the manual (tc_manual.inc) to stdout. */
int tc_misc_manual(void) {
    tc_puts(tc_manual_text);
    return TC_EXIT_OK;
}

/* --emit-fish-completions: part A, the default config path the Python
   splices in (shorten_path(DEFAULT_CONFIG_PATH)), then part B. */
int tc_misc_fish(void) {
    char path[MISC_PATH_SZ];
    size_t len;

    memset(path, 0, sizeof(path));
    len = tc_default_config_path(path, sizeof(path));
    if (len == 0 || len >= sizeof(path)) {
        /* no XDG/HOME default: fall back to the passwd home like the
           Python's Platform class (Linux _xdg / macOS expanduser) */
        char home[MISC_PATH_SZ];
        if (tc_expanduser("~", home, sizeof(home)) > 0) {
            len = (size_t)snprintf(path, sizeof(path),
                                   "%s/.config/twitch-counts.toml", home);
        }
    }
    tc_puts(tc_fish_text_a);
    if (len > 0 && len < sizeof(path)) {
        tc_puts(tc_shorten_path(path));
    }
    tc_puts(tc_fish_text_b);
    return TC_EXIT_OK;
}

/* --complete KIND: candidates for channels/groups/dates/weeks/periods/
   users/includes, one per line; a failure prints the quiet ConfigError
   report and returns 0 (never a loud exit). */
int tc_misc_complete(const tc_opts *opts) {
    misc_state st;
    int status;

    memset(&st, 0, sizeof(st));
    st.opts = opts;
    misc_names_init(&st.names);
    misc_excl_init(&st.excl);

    status = misc_config_open(&st);
    if (status != 0) {
        misc_state_free(&st);
        return TC_EXIT_OK;
    }
    switch (opts->complete_kind) {
    case TC_COMPLETE_CHANNELS:
        misc_complete_channels(&st);
        break;
    case TC_COMPLETE_GROUPS:
        misc_complete_groups(&st);
        break;
    case TC_COMPLETE_DATES:
        if (misc_require_channel(&st) == 0) {
            misc_complete_dates(&st);
        }
        break;
    case TC_COMPLETE_WEEKS:
        if (misc_require_channel(&st) == 0) {
            misc_complete_weeks(&st);
        }
        break;
    case TC_COMPLETE_PERIODS:
        if (misc_require_channel(&st) == 0) {
            misc_complete_periods(&st);
        }
        break;
    case TC_COMPLETE_USERS:
        if (misc_require_channel(&st) == 0) {
            misc_complete_users(&st);
        }
        break;
    case TC_COMPLETE_INCLUDES:
        if (misc_require_channel(&st) == 0) {
            misc_complete_includes(&st);
        }
        break;
    default:
        /* the CLI validates the kind, so a bad enum is a programming error;
           completion still never fails loudly — report it and return 0 */
        misc_failed(&st, "internal error: unknown --complete kind");
        break;
    }
    misc_state_free(&st);
    return TC_EXIT_OK;
}

/* The current time in UTC as (packed YYYYMMDD, seconds-of-day).  Documented
   deviation: the Python's misc_complete_users uses datetime.now() (local
   time); the port uses UTC so the window is reproducible. */
void tc_misc_now_utc(int64_t *ymd, int64_t *sod) {
    struct timespec ts;
    time_t now;
    if (clock_gettime(CLOCK_REALTIME, &ts) == 0) {
        now = ts.tv_sec;
    } else {
        now = time(NULL);
    }
    tc_epoch_to_ymd_sod((int64_t)now, ymd, sod);
}